jet_angle = 0;
firing = false;
warning = false;
stream_progress = 0;
fire_duration = 90;        // was 90 — fires half as long
warning_duration = 120;    // was 60 — warning twice as long
cooldown_duration = 300;   // was 180 — much longer between fires
state = "idle";
state_timer = random_range(200, 360); // was 120-240, longer before first fire